addons:
  apt:
    packages:
      - apache2
      - language-pack-nl
      - libapache2-mod-fastcgi

install:
  - echo "Initializing Apache2 and PHP-FPM"
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - tests/Resources/apache2/apache2.sh