language: php
sudo: false

php:
  - 5.4
services:
  - mysql
addons:
  apt:
    packages:
      - apache2
      - language-pack-nl
      - libapache2-mod-fastcgi
before_install:
  - pwd
  - ls
  - mysql -e "create database pmttest;" -uroot
  - mysql -e "use pmttest;"
  - mysql -e "CREATE TABLE IF NOT EXISTS pmt_attempts (
                attempt_id int(11) NOT NULL AUTO_INCREMENT,
                attempt_percent_mark float NOT NULL,
                attempt_time_start varchar(255) NOT NULL,
                attempt_time_end varchar(255) NOT NULL,
                attempt_complete enum(''Y'',''N'') NOT NULL,
                course_id int(11) NOT NULL,
                user_id int(11) NOT NULL,
                order_id int(11) NOT NULL,
                PRIMARY KEY (attempt_id)
              ) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1186 ;"

install:
  - echo "Initializing Apache2 and PHP-FPM"
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - chmod +x tests/Resources/apache2/apache2.sh
  - tests/Resources/apache2/apache2.sh
  - curl localhost:8080/index.html
script:
 # Update the permalink structure.
   - curl localhost/index.html -I
   - curl localhost/index.html
   - curl localhost/index.html
   - curl localhost:8080
   - curl localhost:8080/index.html