user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
task:
    resource: "@TaskBundle/Controller/"
    type:     annotation
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
partnership:
    resource: "@PartnershipBundle/Controller/"
    type:     annotation
api_bundle:
    type: rest
    prefix: /api
    resource: "@ApiBundle/Resources/config/routing.yml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc